version: '3'

services: 
  app:
    container_name: containernode
    restart: always
    build: .
    ports:
      - "8000:6000"

    links:
      - mongo

    volumes:
      - .:/usr/app

  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27018:27017"

